### ISSUE TITLE
When handling SIGTERM, the process no longer exits

### ISSUE THREAD

**Issue by apechimp** [jprichardson/node-death#3]
I've noticed that since `death` handles SIGINT, [node no longer exists](http://nodejs.org/api/process.html#process_signal_events) when it receives SIGINT.

**Comment by jprichardson** [comment]
I'm not sure that I understand. What do you mean by "node no longer exists" and what are the repercussions of this?

**Comment by apechimp** [comment]
Ahh sorry! Typo! node no longer _exits_. Because SIGINT has been handled, the node process doesn't exist. This is causing a problem for me on heroku where it receives the signal to shutdown, but the process never dies, so heroku logs that as an error.

**Comment by jprichardson** [comment]
Ah, I see. So maybe some kind of flag to actually allow the exit or something like that? Would a short term fix work to just manually call `process.exit()` when the signal is `sigint`?

So, in other words, something like this:

```js
var ON_DEATH = require('death')

ON_DEATH(function(signal, err) {
  if (signal === 'SIGINT')
    process.exit()
})
```

?

**Comment by apechimp** [comment]
Yes, and similarly for `SIGTERM`. That is a good work around. Would adding `process.exit` to death be a welcome PR?

**Comment by apechimp** [comment]
Actually, on second thought, death probably shouldn't be concerned with that. I'll do the signal check as you suggested. Thanks!
