### ISSUE TITLE
Update the npm module with the ability to remove event listeners

### ISSUE THREAD

**Issue by NickMackz** [jprichardson/node-death#5]
The code on here has the ability to remove event listeners, but the npm hosted module has never been updated to include this. Would it be possible to update it?

**Comment by jprichardson** [comment]
Done. Sorry about the delay.

**Comment by dandv** [comment]
Is this working as intended? If I press ^C after running the script below, it does *not* abort:

```js
var ON_DEATH = require('death'); //this is intentionally ugly

ON_DEATH(function(signal, err) { console.log('croak'); })

setTimeout(function () {}, 10000);
```

Without ON_DEATH, the script aborts after I press ^C once.

**Comment by NickMackz** [comment]
You need to kill the process in your ON_DEATH function.

```javascript
var ON_DEATH = require('death'); //this is intentionally ugly

ON_DEATH(function(signal, err) {
  console.log('croak'); 
  process.kill(process.pid, signal);
})

setTimeout(function () {}, 10000);
```
